#!/bin/bash

# correctness of setup
ASEDIR=$(grep -E "^ASE_DIR=.*" "$ASEMANAGEPROGRAM/config" | tr -s " " | cut -d "=" -f2 )
if [[ ! -d "$ASEDIR" ]]; then
        echo "config right ase toolchain project's path"
        exit 1
fi

# declare array
declare -a programs

# extract dirs of all programs
find "$ASEDIR/programs/" -mindepth 1 -maxdepth 1 > ./tmp.txt
if [[ $(cat ./tmp.txt | wc -l) -eq 0 ]]; then
	echo "There is nothing to delete"
	rm ./tmp.txt
	exit 1
fi

# loop to populate the array
ind=0
while read -r line; do
	programs[$ind]="$line"
	echo -e "$ind) \t ${line##*/}"
	((ind++))
done < ./tmp.txt


# read from ans
echo -n "Choose program to delete: "
read -r ans
dim=${#programs[@]}
if [[ ! $ans =~ ^[0-9]*$ || $ans -ge $dim  ]]; then
	echo "Wrong number"
	rm ./tmp.txt
	exit 1
fi


# delete selected dir
rm -rf "${programs[$ans]}"

# final prints
find "$ASEDIR/programs/" -mindepth 1 -maxdepth 1 > ./tmp.txt
if [[ $(cat ./tmp.txt | wc -l) -eq 0  ]]; then
	echo "no remaining programs"
	rm ./tmp.txt
	exit 0
fi
echo "remaining programs:"
while read -r line; do
        echo -e "${line##*/}"
done < ./tmp.txt
rm ./tmp.txt

