#!/bin/bash

help(){
	echo "Usage:"
	echo " ase_sim [OPTIONS] [--]"
	echo " ase_sim [OPTIONS]"
	echo " ase_sim -a|--add=<file>"
	echo " ase_sim -l|--latencies=<arg1><arg2>...<arg6>"
	echo " ase_sim -a|--add=<file> -l|--latencies=<arg1><arg2>...<arg6>"
	echo " ase_sim -o|-out"
	echo " ase_sim -o|-out -t"
	echo " ase_sim -i|--in=<folder_dest>"
	echo "Options:"
	echo -e " -h --help \t Show this screen"
	echo -e " -a --add = <file> \t Add a new program (it should not exist yet)"
	echo -e " -lt --latencies = <arg1><arg2>...<arg6> \t Set the latencies"
	echo -e " -t --table \t Produce the pipeline table in .xlsx file (only for WSL2 users) toward Documents folder in windows"
	echo -e " -i --in = <folder_dest> \t Path to move all results file (do not confuse with simulate.sh option)"
	echo -e " -o --out \t Simulate program with out of order architecture (using Konata)"
}

modify_latency(){
	if [[ "$#" -ne 6 ]]; then
		echo "Wrong number of args"
		help
		exit 1
	fi
	arg=("$@")
	for par in "${arg[@]}"; do
        	if [[ ! $par  =~ ^[1-9][0-9]*$  ]]; then
					echo "Wrong arguments"
					help
                	exit 1
        	fi
	done
	latencies=('INTEGER_ALU_LATENCY'\
		'INTEGER_MUL_LATENCY' \
		'INTEGER_DIV_LATENCY' \
		'FLOAT_ALU_LATENCY' \
		'FLOAT_MUL_LATENCY' \
		'FLOAT_DIV_LATENCY')
	for ((i=0; i<"${#latencies[@]}"; i++)); do
        	lat="${latencies[$i]}"
        	val="${arg[$i]}"
        	sed -i "s/^$lat = .*/$lat = $val/" "$ASEDIR/gem5/riscv_in_order_hen_patt.py"
    	done
	sed -i 's/\r//' "$ASEDIR/gem5/riscv_in_order_hen_patt.py"
}

add_program(){
	# extract basename
	DIR="$1"
	FILENAME=${DIR##*/}
	BASENAME=${FILENAME%%.[sc]}
	# if program does not exist yet
	if [[ ! -d "$ASEDIR/programs/$BASENAME" ]]; then
		ase_add $DIR 
	fi
	sim_option="-i $ASEDIR/programs/$BASENAME $sim_option"
}

WORKDIR="$(pwd)"
folder_dest="$WORKDIR"

# getting options
flag_gen=0
flagi=0
sim_option=""
if [[ -n $1 && ! "$1" =~ ^- && ! "$1" == "--" ]]; then
	echo "Wrong option"
	exit 1
fi
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do jump=1; case $1 in
  	-a | --add )
		shift
		if [[ ! -f $1 ]]; then
			echo "No such file"
			help
			exit 1
		fi
		add_program $1
		;;
	-i | --in )
		shift
		flagi=1
		folder_dest=$1
		if [[ ! -d $folder_dest ]]; then
			mkdir $folder_dest
		fi
		;;
  	-lt | --latencies )
		shift
		arg=("${@:1:6}")
		modify_latency "${arg[@]}"
		jump=6
		;;
	-t | --table )
		if [[ -n $(echo uname -r | grep -e "WSL2") ]]; then
			echo "This kernel is wrong"
			exit 1
		fi
		if [[ -n $(cat /etc/wsl.conf | tr -d " " | grep -e "appendWinsowsPath=false") ]]; then
			echo "Windows PATH not included"
			exit 1
		fi
		if [[ -z $(which python3) ]]; then
			echo "python3 is missing"
			exit
		fi
		gen_flag=1
		;;
	-o | --out )
		# TODO
		;;
	-h | --help )
		help
		exit
		;;
	* )
		echo "Wrong option"
		help
		exit 1
esac; shift $jump; done
if [[ "$1" == '--' ]]; then shift; fi


# launch sim
cd $ASEDIR
echo "simulate.sh $sim_option"
source simulate.sh $sim_option

if [[ $? -ne 0 ]]; then
	echo "Something gone wrong during simulation"
	exit 1
fi

# final print
cd "$WORKDIR"
act_program_folder="/$ASEDIR/$program_folder"
if [[ $flagi -eq 1 ]]; then
	act_program_folder=$program_folder
fi
cp -v "$ASEDIR/results/$program/stats.txt" "$folder_dest/stats_$program.txt"
# cp -v "$program_folder/trace.out" "$folder_dest/trace.out"
echo -e "\n ################# Opening file dump ... #################### \n"
cp -v "$act_program_folder/$program.dump" "$folder_dest/$program.dump"
cat "$act_program_folder/$program.dump"
# create pipeline table
if [[ -f "$ASEDIR/programs/$program/$program.s" ]]; then
	python3 "$ASEMANAGEPROGRAM/generate_pipeline_table.py" "$ASEDIR/programs/$program/$program.s"
	if [[ $gen_flag -eq 1 ]]; then
		echo -e "\n #################### Opening excel file ################### \n"
		DIRUSER=$(cmd.exe /c echo %USERPROFILE% | tr -d '\r')
		WINUSER="${DIRUSER##*\\}"
		mv "$ASEDIR/programs/$program/$program.xlsx" "/mnt/c/Users/$WINUSER/Documents/$program.xlsx"
		# view doc https://learn.microsoft.com/it-it/windows/wsl/filesystems
		powershell.exe start "C:\\Users\\$WINUSER\\Documents\\$program.xlsx"
	else
		mv "$ASEDIR/programs/$program/$program.xlsx" "$folder_dest/$program.xlsx"
	fi
fi
echo -e "\n ######################## Latencies ######################### \n"
latencies=('INTEGER_ALU_LATENCY'\
		'INTEGER_MUL_LATENCY' \
		'INTEGER_DIV_LATENCY' \
		'FLOAT_ALU_LATENCY' \
		'FLOAT_MUL_LATENCY' \
		'FLOAT_DIV_LATENCY')
for ((i=0; i<"${#latencies[@]}"; i++)); do
	lat="${latencies[$i]}"
	echo "$(grep -e "^$lat = [0-9]*$" "$ASEDIR/gem5/riscv_in_order_hen_patt.py")"
done