#!/bin/bash

help(){
	echo "Usage:"
	echo " ase_sim [OPTIONS] [--]"
	echo " ase_sim [OPTIONS]"
	echo " ase_sim -a|--add=<file>"
	echo " ase_sim -l|--latencies=<arg1><arg2>...<arg6>"
	echo " ase_sim -a|--add=<file> -l|--latencies=<arg1><arg2>...<arg6>"
	echo "Options:"
	echo -e " -h --help \t Show this screen"
	echo -e " -a --add = <file> \t Add a new program (it should not exist yet)"
	echo -e " -lt --latencies = <arg1><arg2>...<arg6> \t Set the latencies"
	echo -e " -t --table \t Produce the pipeline table in .xlsx file (only for WSL2 users) toward Documents folder in windows"
}

modify_latency(){
	if [[ "$#" -ne 6 ]]; then
		echo "Wrong number of args"
		help
		exit 1
	fi
	arg=("$@")
	for par in "${arg[@]}"; do
        	if [[ ! $par  =~ ^[1-9][0-9]*$  ]]; then
					echo "Wrong arguments"
					help
                	exit 1
        	fi
	done
	latencies=('INTEGER_ALU_LATENCY'\
		'INTEGER_MUL_LATENCY' \
		'INTEGER_DIV_LATENCY' \
		'FLOAT_ALU_LATENCY' \
		'FLOAT_MUL_LATENCY' \
		'FLOAT_DIV_LATENCY')
	for ((i=0; i<"${#latencies[@]}"; i++)); do
        	lat="${latencies[$i]}"
        	val="${arg[$i]}"
        	sed -i "s/^$lat = .*/$lat = $val/" "$ASEDIR/gem5/riscv_in_order_hen_patt.py"
    	done
	sed -i 's/\r//' "$ASEDIR/gem5/riscv_in_order_hen_patt.py"
}

add_program(){
	# extract basename
	DIR="$1"
	FILENAME=${DIR##*/}
	BASENAME=${FILENAME%%.[sc]}
	# if program does not exist yet
	if [[ ! -d "$ASEDIR/programs/$BASENAME" ]]; then
		ase_add $DIR 
	else
		echo "Program already exists"
	fi
}

# getting options
flag_gen=0
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do jump=1; case $1 in
  	-a | --add )
		shift
		if [[ ! -f $1 ]]; then
			echo "No such file"
			help
			exit 1
		fi
		add_program $1
		;;
  	-lt | --latencies )
		shift
		arg=("${@:1:6}")
		modify_latency "${arg[@]}"
		jump=6
		;;
	-t | --table )
		if [[ -n $(echo uname -r | grep -e "WSL2") ]]; then
			echo "This kernel is wrong"
			exit 1
		fi
		if [[ -n $(cat /etc/wsl.conf | tr -d " " | grep -e "appendWinsowsPath=false") ]]; then
			echo "Windows PATH not included"
			exit 1
		fi
		if [[ -z $(which python3) ]]; then
			echo "python3 is missing"
			exit
		fi
		gen_flag=1
		;;
	-h | --help )
		help
		exit
		;;
	* )
		echo "Wrong option"
		help
		exit 1
esac; shift $jump; done
if [[ "$1" == '--' ]]; then shift; fi


WORKDIR="$(pwd)"
cd $ASEDIR

# launch sim
source ./simulate.sh 

# final print
cp -v "results/$program/stats.txt" "$WORKDIR/stats_$program.txt"
echo -e "\n ################# Opening file dump ... #################### \n"
cp -v "$program_folder/$program.dump" "$WORKDIR/$program.dump"
cat "$program_folder/$program.dump"
# create pipeline table
if [[ -f "$ASEDIR/programs/$program/$program.s" ]]; then
	echo -e "\n #################### Opening excel file ################### \n"
	python3 "$ASEMANAGEPROGRAM/generate_pipeline_table.py" "$ASEDIR/programs/$program/$program.s"
	if [[ $gen_flag -eq 1 ]]; then
		DIRUSER=$(cmd.exe /c echo %USERPROFILE% | tr -d '\r')
		WINUSER="${DIRUSER##*\\}"
		mv "$ASEDIR/programs/$program/$program.xlsx" "/mnt/c/Users/$WINUSER/Documents/$program.xlsx"
		# view doc https://learn.microsoft.com/it-it/windows/wsl/filesystems
		powershell.exe start "C:\\Users\\$WINUSER\\Documents\\$program.xlsx"
	else
		ln "$ASEDIR/programs/$program/$program.xlsx" "$WORKDIR/$program.xlsx"
	fi
fi
echo -e "\n ######################## Latencies ######################### \n"
latencies=('INTEGER_ALU_LATENCY'\
		'INTEGER_MUL_LATENCY' \
		'INTEGER_DIV_LATENCY' \
		'FLOAT_ALU_LATENCY' \
		'FLOAT_MUL_LATENCY' \
		'FLOAT_DIV_LATENCY')
for ((i=0; i<"${#latencies[@]}"; i++)); do
	lat="${latencies[$i]}"
	echo "$(grep -e "^$lat = [0-9]*$" "$ASEDIR/gem5/riscv_in_order_hen_patt.py")"
done

cd "$WORKDIR"